CREATE DATABASE LIBRARY
GO
USE LIBRARY
GO
CREATE TABLE PUBLISHING_HOUSE(
	PH_ID VARCHAR(50) NOT NULL,
	NAME NVARCHAR(255),
	PH_ADDRESS NVARCHAR(1000),
	PHONE_NUMBER VARCHAR(20),
	EMAIL VARCHAR(255),
	PRIMARY KEY(PH_ID)
)
GO
CREATE TABLE BOOK_TYPE(
	BTYPE_ID  INT IDENTITY NOT NULL,
	BTYPE NVARCHAR(255),
	PRIMARY KEY(BTYPE_ID)
)
GO
CREATE TABLE BOOK(
	BOOK_ID VARCHAR(50) NOT NULL,
	NAME NVARCHAR(255),
	AUTHOR NVARCHAR(255),
	PH_ID VARCHAR(50),
	BTYPE_ID INT,
	PRICE MONEY,
	PUBLISH_YEAR INT,
	AMOUNT INT,
	SUMMARY NVARCHAR(1000),
	PRIMARY KEY(BOOK_ID)
)

GO 
CREATE TABLE ACCOUNT(
	USERNAME VARCHAR(255) NOT NULL,
	PASS VARCHAR(255) NOT NULL,
	PRIMARY KEY(USERNAME)
)
GO 
CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID VARCHAR(50) NOT NULL,
	USERNAME VARCHAR(255) NOT NULL,
	NAME NVARCHAR(255),
	EMPLOYEE_ADDRESS NVARCHAR(1000),
	EMAIL VARCHAR(255),
	PHONE_NUMBER VARCHAR(255),
	DATE_OF_BIRTH DATE,
	GENDER INT,
	STARTING_DATE DATE,
	PRIMARY KEY(EMPLOYEE_ID) 
)
GO
CREATE TABLE READER(
	READER_ID VARCHAR(50) NOT NULL,
	NAME NVARCHAR(255),
	DATE_OF_BIRTH DATE,
	READER_ADDRESS NVARCHAR(1000),
	GENDER INT,
	PHONE_NUMBER VARCHAR(20),
	EMAIL VARCHAR(255),
	PRIMARY KEY(READER_ID)
)
GO
CREATE TABLE BORROW_FORM(
	FORM_ID VARCHAR(50) NOT NULL,
	READER_ID VARCHAR(50) NOT NULL,
	EMPLOYEE_ID VARCHAR(50),
	LOAN_DATE DATE,
	EXP_DATE DATE, 
	DEPOSIT MONEY,
	PRIMARY KEY(FORM_ID)

	)
GO
CREATE  TABLE BORROW_DETAILS(
	ID VARCHAR(50) NOT NULL,
	FORM_ID VARCHAR(50) NOT NULL,
	BOOK_ID VARCHAR(50),
	AMOUNT INT,
	PRIMARY KEY(ID,FORM_ID)
)

GO 
CREATE TABLE PAY_FORM(
	ID VARCHAR(50) NOT NULL,
	BORROW_ID VARCHAR(50),
	EMPLOYEE_ID VARCHAR(50),
	PAY_DATE DATE,
	PRIMARY KEY(ID)

)

GO 
CREATE TABLE PAY_DETAILS(
	ID VARCHAR(50) NOT NULL,
	FORM_ID VARCHAR(50) NOT NULL,
	BOOK_ID VARCHAR(50),
	AMOUNT INT,
	PRIMARY KEY(ID,FORM_ID)
)
GO
CREATE TABLE BLACK_LIST(
	ID VARCHAR(50),
	READER_ID VARCHAR(50),
	PRIMARY KEY(ID)
)

GO

ALTER TABLE BLACK_LIST
ADD CONSTRAINT FK_READER_BLACKLIST
FOREIGN KEY (READER_ID) REFERENCES READER(READER_ID);

GO
ALTER TABLE PAY_DETAILS
ADD CONSTRAINT FK_PAYFORM_PAYDETAILS
FOREIGN KEY (FORM_ID) REFERENCES PAY_FORM(ID);


GO
ALTER TABLE PAY_DETAILS
ADD CONSTRAINT FK_BOOK_PAYDETAILS
FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID);

GO
ALTER TABLE PAY_FORM
ADD CONSTRAINT FK_BORRROWFORM_PAYFORM
FOREIGN KEY (BORROW_ID) REFERENCES BORROW_FORM(FORM_ID);

GO
ALTER TABLE BORROW_DETAILS
ADD CONSTRAINT FK_BORROWFORM_BORROWDETAILS
FOREIGN KEY (FORM_ID) REFERENCES BORROW_FORM(FORM_ID);

GO
ALTER TABLE BORROW_DETAILS
ADD CONSTRAINT FK_BOOK_BORROWDETAILS
FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID);

GO
ALTER TABLE BORROW_FORM
ADD CONSTRAINT FK_READER_BORROW_FORM
FOREIGN KEY (READER_ID) REFERENCES READER(READER_ID);

GO
ALTER TABLE BORROW_FORM
ADD CONSTRAINT FK_EMPLOYEE_BORROW_FORM
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);

GO
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_ACCOUNT_EMPLOYEE
FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME);

GO
ALTER TABLE BOOK
ADD CONSTRAINT FK_BOOKTYPE_BOOK
FOREIGN KEY (BTYPE_ID) REFERENCES BOOK_TYPE(BTYPE_ID);

GO
ALTER TABLE BOOK
ADD CONSTRAINT FK_PHOUSE_BOOK
FOREIGN KEY (PH_ID) REFERENCES PUBLISHING_HOUSE(PH_ID);












